### ISSUE TITLE
unneeded settings in tsconfig.json and package.json

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Office-Addin-TaskPane#156]
UPDATE 1/9/24: The webpack.config.js change was made in a recent PR. Only the changes to tsconfig.json and package.json still need to be done.

# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

# Expected behavior

webpack.config and tsconfig.json does not have unnecessary/confusing settings

# Current behavior

The following "rule" is in the webpack.config for this template. This would be relevant for the React version, but not for this version. Having this unneeded loader may confuse devs (like me). 
```
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: "ts-loader",
        },
```

The tsconfig.json file has a "jsx" property, with value "react". This "jsx" property should be deleted, because this is not a React project.

Finally, ts-loader should be removed from the package.json. It is not actually doing anything. 

I have tested all these changes and the project works fine.

**Comment by akrantz** [comment]
This is needed for TypeScript, regardless of whether using React.
This is not present in https://github.com/OfficeDev/Office-Addin-TaskPane-JS.

**Comment by akrantz** [comment]
Because both .ts and .tsx are valid extensions for TypeScript files. We don't include any .tsx files by default, but users can add them.

Both loaders are needed. If I remember correctly, the ts-loader handles compiling TypeScript to JavaScript, and Babel handles the polyfills.

**Comment by Rick-Kirkham** [comment]
Sorry, but this is not consistent with my understanding of webpack.config. Polyfills are handled by plug-ins, which is a later section of the webpack.config, not by loaders. This babel loader is configured to transpile `ts` files to JavaScript. 

Yes it is possible that users will convert their add-in to React and add `tsx` files, but they could change the project in lots of ways that would require changing the webpack.config settings. This is just one. It is confusing to have this in a project that doesn't need it.

**Comment by akrantz** [comment]
Ricky, it doesn't hurt anything to keep it like this, but changing does break stuff. Can you please show an example of a React and non-React TypeScript project using a modified webpack config? Because I know specifically that this needs to be this way based on implementing it before.

**Comment by Rick-Kirkham** [comment]
@akrantz I'm not clear on what this means: "show an example of a React and non-React TypeScript project using a modified webpack config". I could create a Yo Office project that uses the React option and then create one that doesn't. And we could then compare them with a tool like Beyond Compare. Is that what you mean? If not, could you elaborate about the ask?

**Comment by akrantz** [comment]
The ask is to demonstrate that there is a problem here which needs fixing. I don't understand why you're asking for changes to be made. It's HELPFUL if the Office-Addin-TaskPane template supports .tsx files even if the base project generated doesn't because developers could add React stuff to it later. It's also HELPFUL that the less we have to have Office-Addin-TaskPane and Office-Addin-TaskPane-React diverge. Furthermore, I have a vague recollection that previously I experimented with different configs here, and the approach taken is both necessary and sufficient. I'm not working on the devx stuff now, but I don't want to waste the other developers time on changes which are not needed.

**Comment by Rick-Kirkham** [comment]
@akrantz Thanks for the clarification. The problem with code or markup that isn't used is that its presence confuses developers, especially a developer who's trying to troubleshoot something. I discovered this issue while trying to write an overview introduction article to Yo Office. (It's one of many puzzles that I've come across while looking at these templates, but so far, for all of the others I've eventually discovered why the puzzling thing is the way it is.)

I'm not convinced by "because developers could add React stuff to it later" because there are LOTS of things the developer _could_ add later. But we rightly don't add a loader for all of them. (Just look at all the loaders listed [here](https://webpack.js.org/loaders/). And that's only the ones that WebPack itself produces. There are many more, like ts-loader.) 

Moreover, React isn't something you "add" to a web app. To switch to React would mean a complete change of architecture to a single-page app. This is one of the least likely changes a developer would make to an existing add-in. It would make far more sense if they really wanted to switch to React to create a new project that uses the React option, and then copy code over as needed from the original project. 

I'll try to remove the loader myself and see if anything breaks and report back here.

**Comment by Rick-Kirkham** [comment]
@akrantz I have confirmed that the project works fine even if all references to ts-loader (and react) are removed from the files, including webpack.config, tsconfig.json, and package.json. So, I'll try to create a PR in the template repo with these changes.

**Comment by Rick-Kirkham** [comment]
I gave up trying to fix this myself. How/whether to change the package-lock.json was too complicated. So, I've just assigned this to @millerds
