### ISSUE TITLE
The reference to the fabric.min.css in taskpane.html is yielding a 404 - not found error

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/Office-Addin-TaskPane#160]
# Expected behavior

I would expect the stylesheet used by the task pane to download and that the task pane is styled using the styles in the downloaded CSS.

# Current behavior

The download https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.1/css/fabric.min.css in taskpane.html consistently result in a 404 - Not Found error.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use yo office to create a Custom Functions add-in with a task pane
2. Debug in Excel Desktop or Excel Web and open the add-in

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

taskpane.html:1 
        
         GET https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.1/css/fabric.min.css net::ERR_ABORTED 404

**Comment by millerds** [comment]
The template is outputting a link to version 9.6.1 of fabric.min.css.  I can't say if version 11.01 is published to the CDN in order to download it.  This is not a problem with the template, but rather the desired file from a user change not being available.
