### ISSUE TITLE
Outlook Add-in with unified Microsoft 365 Manifest (preview) fails on sideloading

### ISSUE THREAD

**Issue by urig** [OfficeDev/Office-Addin-TaskPane#206]
##  Expected behavior

After completing the generation of an add-in prokect, running it was expected to successfully start "webpack dev server".

##  Current behavior

"Webpack dev server" seems to successfully start in a new window but in the original Terminal window, `npm` outputs the following errors and exits:

##  Steps to Reproduce
1. On Windows 10, as per instructions in [quickstart](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest) installed node LTS (v18.16.0), yo v4.3.1 and latest version of office generator.
2. In an elevated Terminal session, ran `yo office` and chose `Outlook Add-in with unified Microsoft 365 Manifest (preview)` as project type.
3. Once generator was done, ran `npm start`.

## Context

* Operating System:
Windows 10
* Node version:
LTS (v18.6.0)
* Tool version:
Yeoman v4.3.1, latest `office` generator

## Failure Logs

Errors appearing in `npm` output before exit:

```
running: npx @microsoft/teamsfx-cli m365 sideloading --file-path C:\Users\REDACTED\AppData\Local\Temp\manifest.zip

Using account REDACTED
Uploading package ...
Acquiring package ...
Acquire done. App TitleId: U_e17399ab-af80-a3fc-2780-c43cdf3de208
Checking acquired package ...

--Error sideloading!--
Error: Error: Command failed: npx @microsoft/teamsfx-cli m365 sideloading --file-path C:\Users\REDACTED\AppData\Local\Temp\manifest.zip
This command is in preview.
(×) Sideloading failed.
(×) {"error":{"code":"InternalServerError","message":"There was an error processing the request"}}
(×) [Core.Error]: Request failed with status code 500

STDERR:
This command is in preview.
(×) Sideloading failed.
(×) {"error":{"code":"InternalServerError","message":"There was an error processing the request"}}
(×) [Core.Error]: Request failed with status code 500

Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Command failed: npx @microsoft/teamsfx-cli m365 sideloading --file-path C:\Users\REDACTED\AppData\Local\Temp\manifest.zip
This command is in preview.
(×) Sideloading failed.
(×) {"error":{"code":"InternalServerError","message":"There was an error processing the request"}}
(×) [Core.Error]: Request failed with status code 500
```

**Comment by AlexJerabek** [comment]
Thank you for reporting this @urig.

@millerds, could you please investigate?

**Comment by millerds** [comment]
@urig can you open Outlook and see if the add-in is loaded in the ribbon?

**Comment by Rick-Kirkham** [comment]
Closing this issue for now. @urig If you are still seeing this problem, you can ask to reopen the issue.

**Comment by urig** [comment]
Hi @Rick-Kirkham. I tried reproducing the issue and was unable to. Thanks for closing this.

**Comment by virus2016** [comment]
Hi @Rick-Kirkham, I am facing this issue on Mac: 

```Debugging is being started...
App type: desktop
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Manifest package saved to /tmp/manifest.zip
running: npx @microsoft/teamsfx-cli@2.0.2-alpha.4f379e6ab.0 m365 sideloading --file-path /tmp/manifest.zip

Using account calum.macrae@medayo.com
Uploading package ...
Acquiring package ...
TitleId: U_870b656c-df83-c3e7-b18b-82c81bbbaf65
AppId: ab1f1cd3-0ca6-4040-ba20-4a69cebdcb0a
Sideloading done.

Successfully registered package! (U_870b656c-df83-c3e7-b18b-82c81bbbaf65)
 STDERR: (!) Warning: This command is in preview.


Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Sideload to the Outlook app is not supported.
```

Is this the same bug?

**Comment by Rick-Kirkham** [comment]
@virus2016 Your error message is different. Please open a new Issue.

**Comment by virus2016** [comment]
Opened 🫡
