### ISSUE TITLE
Missing script: "start:desktop" when F5

### ISSUE THREAD

**Issue by jayzhang** [OfficeDev/Office-Addin-TaskPane#282]
# Prerequisites

# Expected behavior

Successfully launch F5.

# Current behavior

F5 failed because of missing "start:desktop" script: 
![image](https://github.com/user-attachments/assets/1196ca0f-16ce-4e9a-a201-c6ad873a6379)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. download: https://github.com/OfficeDev/Office-Addin-TaskPane/archive/yo-office.zip
2. unzip and open it with VS Code
3. execute script: `npm run convert-to-single-host -- outlook json`
4. F5 to launch local debug

## Context

In package.json, there is no script "start:desktop": 
```json
"scripts": {
    "build": "webpack --mode production",
    "build:dev": "webpack --mode development",
    "dev-server": "webpack serve --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "signin": "office-addin-dev-settings m365-account login",
    "signout": "office-addin-dev-settings m365-account logout",
    "start": "office-addin-debugging start appPackage/manifest.json",
    "stop": "office-addin-debugging stop appPackage/manifest.json",
    "validate": "office-addin-manifest validate appPackage/manifest.json",
    "watch": "webpack --mode development --watch"
  }
```
## Failure Logs

Related bug workitems: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30160931

**Comment by millerds** [comment]
This should be fixed now.
