### ISSUE TITLE
readme and contributor files install with yo office

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/Office-Addin-TaskPane#93]
I notice when running yo office that the entire repo gets copied into my new project including the README.md and CONTRIBUTING.md. In the context of a developer creating a new project that does not know there are repos behind the templates, these are awkward when viewing and reading files in the project structure in VS Code.

The readme refers to the repo (but in a new project a developer is likely using their own repo.)
The contributing.md talks about contributing to a sample (but this is a new project, not sample code.)

I recommend moving all the template parts that should get installed into a template folder so you can keep the readme and contributing files separated (or have a different readme that makes sense after you create a new project). Basically the root of the repo would be files specific to this repo and how it operates. Template folder contains the folder/file structure to copy down for new yo office install.

**Comment by akrantz** [comment]
The repository is the template, but there is a way to remove unwanted files from the repository when yo office clones the template. These files can easily be added to that list.

**Comment by TCourtneyOwen** [comment]
Easy fix, I can send out a PR for that today

**Comment by TCourtneyOwen** [comment]
Fix has been submitted to office-add-taskpane.  we still need to merge this change across all project template repos, so leaving this issue open until that's done

**Comment by akrantz** [comment]
@TCourtneyOwen @davidchesnut Please verify that this is now complete and close. Thanks.

**Comment by TCourtneyOwen** [comment]
I believe this is done.  Closing

**Comment by akrantz** [comment]
I just looked at the "master" branch, and convertToSingleHost.js will remove the readme file. 

@darrelmiller After the latest round of merging Office-Addin-TaskPane to the other templates, we will need the release the updates by merging the "master" branch to the "yo-office" branch for each template.

**Comment by millerds** [comment]
Just verified this has be fixed in the yo-office branch
